[package]
name = "godot4-prebuilt"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "ffi"]
categories = ["game-engines", "graphics"]
publish = false

[dependencies]
