name: "Build Godot artifacts"

on:
  workflow_dispatch:
    inputs:
      godot-version:
        description: 'Version to build (for example "4.0.1")'
        required: true

defaults:
  run:
    shell: bash

jobs:
  download-godot:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
#      - uses: actions/checkout@v3
      - name: "Prepare versions"
        run: |
          version="${{ github.event.inputs.godot-version }}"
          
          # if version has already suffix (e.g. -rc1), leave as-is, but replace filePath
          if [[ $1 =~ "-" ]]; then
            filePath=$(echo "$version" | sed "s!-!/!")
          else
            filePath="$version"
            version="${version}-stable"
          fi
          
          filename=Godot_v${version}_linux.x86_64
          
          echo "GODOT4_FILE_URL=$filePath/$filename.zip" >> $GITHUB_ENV
          echo "GODOT4_BIN=godot_bin/$filename" >> $GITHUB_ENV
          echo "GODOT4_VER=$version" >> $GITHUB_ENV

      - name: "Download Godot ${{ env.GODOT4_VER }}..."
        # for gdnative: wget --no-verbose "https://downloads.tuxfamily.org/godotengine/$filePath/Godot_v${{ inputs.godot_ver }}_linux_headless.64.zip" -O /tmp/godot.zip
        run: |          
          wget --no-verbose "https://downloads.tuxfamily.org/godotengine/$GODOT4_FILE_URL" -O ${{ runner.temp }}/godot.zip || {
            echo "::error::Godot version '$GODOT4_VER' not available online."
            exit 1
          }
          unzip -o ${{ runner.temp }}/godot.zip -d godot_bin

      - name: "Download GDExtension header..."
        run: wget https://raw.githubusercontent.com/godotengine/godot/$GODOT4_VER/core/extension/gdextension_interface.h -P godot_bin

      - name: "List dir"
        run: ls -la godot_bin

      - name: "Invoke Godot"
        run: $GODOT4_BIN --version

